version: '3'
services:
  anestech-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    volumes:
    - .:/usr/src/app
    container_name: anestech_api
    environment:
      - SERVER_ENV=development
    depends_on:
      - anestech-db
    networks:
      - anestech-api-network

  anestech-db:
    container_name: anestech-db
    image: mysql:5.6
    ports:
      - "3306:3306"
    networks:
      - anestech-api-network
    volumes:
      - ../backend/storage/mysql/mysql_conf_d:/etc/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}

networks:
  anestech-api-network:
      driver: bridge
