version: '3'
services:
  anestech-api:
    container_name: anestech_api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - SERVER_ENV=development
    depends_on:
      - anestech-db
    ports:
      - "3333:3333"
      - "80:80"
    networks:
      - anestech-api-network
    volumes:
      - ../backend:/code
      - ../backend/storage/logs:/tmp/logs
  anestech-db:
    container_name: anestech_db
    image: mysql:5.6
    ports:
      - "3306:3306"
    networks:
      - anestech-api-network
    volumes:
      - ../backend/storage/mysql/mysql_conf_d:/etc/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=anestech
      - MYSQL_DATABASE=anestech

networks:
  anestech-api-network:
      driver: bridge
